/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      "avatars.githubusercontent.com",
      "ichef.bbci.co.uk",
      "static.politico.com",
      "www.washingtonpost.com",
      "cdn.mos.cms.futurecdn.net",
      "media-cldnry.s-nbcnews.com",
      "www.politico.eu",
      "image.cnbcfm.com",
      "media.cnn.com",
      "dims.apnews.com",
      "gsp-image-cdn.wmsports.io",
      "variety.com",
      "assets2.cbsnewsstatic.com",
      "assets.bwbx.io",
      "www.ft.com",
      "www.cleveland.com",
      "d3i6fh83elv35t.cloudfront.net",
      "thedebrief.b-cdn.net",
      "npr.brightspotcdn.com",
      "wordpress-assets.futurism.com",
      "images.axios.com",
      "deadline.com",
      "www.videogameschronicle.com",
      "images.mlssoccer.com",
      "oaklandside.org",
      "www.sciencealert.com",
      "i0.wp.com",
      "hips.hearstapps.com",
      "spacenews.com",
      "media.zenfs.com",
      "www.hollywoodreporter.com",
      "img.ksl.com",
      "s.hdnux.com",
      "livenews.foxnews.com",
      "platform.theverge.com",
      "minnesotareformer.com",
      "cdn.hoopsrumors.com",
      "www.wweek.com",
      "files.anash.org",
      "static.foxnews.com",
      "www.rollingstone.com",
      "photos5.appleinsider.com",
      "techcrunch.com"
    ],
  },
};

module.exports = nextConfig;
