/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      "variety.com",
      "cdn.mos.cms.futurecdn.net",
      "cdn.arstechnica.net",
      "cdn-8.motorsport.com",
      "nbcsports.brightspotcdn.com",
      "www.oregonlive.com",
      "wtop.com",
      "s.france24.com",
      "img.buzzfeed.com",
      "techcrunch.com",
      "www.notebookcheck.net",
       "static.politico.com",
      "www.sciencealert.com",
      "www.vvng.com",
       "www.sciencedaily.com",
        "assets.bwbx.io",
          "media.zenfs.com",
          "www.aljazeera.com",
          "images.macrumors.com",
          "assetsio.gnwcdn.com", 
          "npr.brightspotcdn.com",
          "platform.theverge.com",
          "neurosciencenews.com",
          "d.newsweek.com",
           "www.investopedia.com",
           "a2.espncdn.com",
            "static.toiimg.com",
            "images.axios.com",
            "www.hollywoodreporter.com",
            "images.barrons.com",
             "media.wired.com",
             "static.972mag.com",
             "bnetcmsus-a.akamaihd.net",
             "cdn.abcotvs.com",
             "pyxis.nymag.com",
             "thespun.com",
             "www.washingtonpost.com",
             "www.nascar.com",
             "images.ctfassets.net",
             "deadline.com",
             "dims.apnews.com",
             "avatars.githubusercontent.com",
             "ichef.bbci.co.uk",
             "media.cnn.com",
             "www.hindustantimes.com",
             "i0.wp.com"
    ],
  },
};

module.exports = nextConfig;
